/**
 * CINEMASTELLAR - Catálogo Central de Películas, Horarios y Confitería
 * Arquitectura de Datos Oficial - Google Cloud OKF v0.2
 * Autor: Mileidys Agamez Ospino
 */

const CINEMA_MOVIES = [
  {
    id: "mov-dune-2",
    title: "Dune: Parte Dos",
    originalTitle: "Dune: Part Two",
    genre: "Ciencia Ficción",
    genres: ["Ciencia Ficción", "Aventura", "Acción"],
    year: 2024,
    duration: "166 min",
    ageRating: "+13",
    rating: 8.9,
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    poster: "assets/images/dune.jpg",
    backdrop: "assets/images/cinema_hero_banner.jpg",
    badge: "ESTRENO IMAX",
    priceBase: 18000,
    vipPrice: 26000,
    formats: ["IMAX 3D", "2D", "D-BOX"],
    showtimes: ["14:30", "17:45", "21:00"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/Way9Dexny3w?autoplay=1",
    synopsis: "Paul Atreides se une a Chani y a los Fremen mientras busca venganza contra los conspiradores que destruyeron a su familia. Al enfrentarse a una elección entre el amor de su vida y el destino del universo conocido, se esfuerza por evitar un futuro terrible que solo él puede prever.",
    featured: true
  },
  {
    id: "mov-hungergames",
    title: "Los Juegos del Hambre: Balada de Pájaros Cantores",
    originalTitle: "The Ballad of Songbirds and Snakes",
    genre: "Acción",
    genres: ["Acción", "Aventura", "Ciencia Ficción"],
    year: 2023,
    duration: "157 min",
    ageRating: "+13",
    rating: 8.4,
    director: "Francis Lawrence",
    cast: ["Tom Blyth", "Rachel Zegler", "Peter Dinklage", "Hunter Schafer"],
    poster: "assets/images/juegos_del_hambre.jpg",
    backdrop: "assets/images/cinema_hall.jpg",
    badge: "ÉXITO DE TAQUILLA",
    priceBase: 16000,
    vipPrice: 24000,
    formats: ["2D", "IMAX 2D"],
    showtimes: ["15:15", "18:30", "21:45"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/RDE6Uz73A7g?autoplay=1",
    synopsis: "Años antes de convertirse en el tiránico presidente de Panem, el joven de 18 años Coriolanus Snow es la última esperanza para su linaje desvanecido. Con los 10º Juegos del Hambre anuales acercándose, se alarma cuando es asignado como mentor de Lucy Gray Baird.",
    featured: true
  },
  {
    id: "mov-divergent",
    title: "Divergente: Insurgente",
    originalTitle: "The Divergent Series: Insurgent",
    genre: "Ciencia Ficción",
    genres: ["Ciencia Ficción", "Acción", "Aventura"],
    year: 2023,
    duration: "139 min",
    ageRating: "+13",
    rating: 7.8,
    director: "Robert Schwentke",
    cast: ["Shailene Woodley", "Theo James", "Kate Winslet", "Miles Teller"],
    poster: "assets/images/divergente.jpg",
    backdrop: "assets/images/cinema_tech.jpg",
    badge: "DISTOPÍA",
    priceBase: 15000,
    vipPrice: 22000,
    formats: ["2D", "3D"],
    showtimes: ["14:00", "16:45", "19:30"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/sX9-l0iO5w8?autoplay=1",
    synopsis: "Tris y Cuatro son ahora fugitivos cazados por Jeanine, la líder de la élite de Erudición hambrienta de poder. Corriendo contra el tiempo, deben averiguar qué protegió la familia de Tris a costa de sus vidas.",
    featured: false
  },
  {
    id: "mov-damsel",
    title: "Damsel: La Doncella",
    originalTitle: "Damsel",
    genre: "Acción",
    genres: ["Acción", "Fantasía", "Aventura"],
    year: 2024,
    duration: "110 min",
    ageRating: "+13",
    rating: 7.6,
    director: "Juan Carlos Fresnadillo",
    cast: ["Millie Bobby Brown", "Angela Bassett", "Robin Wright", "Nick Robinson"],
    poster: "assets/images/la_doncella.jpg",
    backdrop: "assets/images/cinema_hall.jpg",
    badge: "FANTASÍA ÉPICA",
    priceBase: 15000,
    vipPrice: 22000,
    formats: ["2D", "IMAX 2D"],
    showtimes: ["16:00", "18:45", "21:15"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/iM150ZWovZM?autoplay=1",
    synopsis: "Una obediente damisela acepta casarse con un apuesto príncipe, solo para descubrir que la familia real la ha reclutado como un sacrificio para pagar una antigua deuda en las cavernas de un dragón voraz.",
    featured: true
  },
  {
    id: "mov-purplehearts",
    title: "Corazones Malheridos",
    originalTitle: "Purple Hearts",
    genre: "Romance",
    genres: ["Romance", "Drama", "Música"],
    year: 2023,
    duration: "122 min",
    ageRating: "+13",
    rating: 8.1,
    director: "Elizabeth Allen Rosenbaum",
    cast: ["Sofia Carson", "Nicholas Galitzine", "Chosen Jacobs"],
    poster: "assets/images/corazones_malheridos.jpg",
    backdrop: "assets/images/fondo_romance.jpg",
    badge: "ROMANCE TOP",
    priceBase: 14000,
    vipPrice: 20000,
    formats: ["2D"],
    showtimes: ["15:00", "17:30", "20:00"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/WFNl9hpkX-E?autoplay=1",
    synopsis: "Una aspirante a cantante con diabetes tipo 1 y un marine en aprietos económicos acuerdan contraer matrimonio de conveniencia por los beneficios militares, pero el destino transforma el pacto en una pasión real.",
    featured: false
  },
  {
    id: "mov-prettywoman",
    title: "Pretty Woman: Mujer Bonita",
    originalTitle: "Pretty Woman",
    genre: "Romance",
    genres: ["Romance", "Comedia"],
    year: 2024,
    duration: "119 min",
    ageRating: "+14",
    rating: 8.5,
    director: "Garry Marshall",
    cast: ["Julia Roberts", "Richard Gere", "Jason Alexander"],
    poster: "assets/images/mujer_bonita.jpg",
    backdrop: "assets/images/fondo_romance.jpg",
    badge: "CLÁSICO 4K",
    priceBase: 14000,
    vipPrice: 20000,
    formats: ["2D Remastered 4K"],
    showtimes: ["16:30", "19:15", "22:00"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/Wzii8kvJ74E?autoplay=1",
    synopsis: "Un exitoso pero solitario magnate de los negocios contrata a una cautivadora dama de compañía para acompañarlo durante una semana de negocios en Beverly Hills.",
    featured: false
  },
  {
    id: "mov-monday",
    title: "¿Qué Pasó con Lunes?",
    originalTitle: "What Happened to Monday",
    genre: "Suspenso",
    genres: ["Suspenso", "Ciencia Ficción", "Acción"],
    year: 2023,
    duration: "123 min",
    ageRating: "+16",
    rating: 8.3,
    director: "Tommy Wirkola",
    cast: ["Noomi Rapace", "Willem Dafoe", "Glenn Close"],
    poster: "assets/images/que_paso_con_lunes.jpg",
    backdrop: "assets/images/cinema_tech.jpg",
    badge: "THRILLER SUSPENSO",
    priceBase: 15000,
    vipPrice: 22000,
    formats: ["2D"],
    showtimes: ["17:15", "19:50", "22:30"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/hOLeOY4wIvw?autoplay=1",
    synopsis: "En un futuro superpoblado gobernado por la ley de hijo único, siete hermanas idénticas nombradas según los días de la semana deben turnarse para salir al exterior con una sola identidad pública.",
    featured: false
  },
  {
    id: "mov-thecall",
    title: "El Teléfono",
    originalTitle: "The Call",
    genre: "Suspenso",
    genres: ["Suspenso", "Terror Psicológico", "Misterio"],
    year: 2023,
    duration: "112 min",
    ageRating: "+16",
    rating: 8.2,
    director: "Lee Chung-hyun",
    cast: ["Park Shin-hye", "Jeon Jong-seo", "Kim Sung-ryung"],
    poster: "assets/images/el_telefono.jpg",
    backdrop: "assets/images/cinema_hall.jpg",
    badge: "MISTERIO",
    priceBase: 15000,
    vipPrice: 22000,
    formats: ["2D Dolby Atmos"],
    showtimes: ["18:00", "20:30", "22:45"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/V6q53_v32qg?autoplay=1",
    synopsis: "Conectadas por un teléfono en la misma casa pero separadas por dos décadas de diferencia temporal, dos mujeres sellan una alianza que desatará una espiral de muerte y cambios aterradores en la realidad.",
    featured: false
  },
  {
    id: "mov-thevow",
    title: "Votos de Amor",
    originalTitle: "The Vow",
    genre: "Romance",
    genres: ["Romance", "Drama"],
    year: 2023,
    duration: "104 min",
    ageRating: "+12",
    rating: 8.0,
    director: "Michael Sucsy",
    cast: ["Rachel McAdams", "Channing Tatum", "Sam Neill"],
    poster: "assets/images/votos_de_amor.jpg",
    backdrop: "assets/images/fondo_romance.jpg",
    badge: "DRAMA ROMÁNTICO",
    priceBase: 14000,
    vipPrice: 20000,
    formats: ["2D"],
    showtimes: ["14:15", "16:45", "19:15"],
    trailerUrl: "https://www.youtube-nocookie.com/embed/9g_2y_v6VfE?autoplay=1",
    synopsis: "Un violento accidente en la nieve borra todos los recuerdos de los últimos cinco años del matrimonio de Paige. Su esposo Leo emprenderá una conmovedora misión para volver a conquistarla.",
    featured: false
  }
];

const CINEMA_SNACKS = [
  {
    id: "snk-combo-estelar",
    name: "Combo Estelar Supremo",
    category: "Combos",
    description: "2 Crispetas Grandes de mantequilla + 2 Gaseosas 32oz + Chocolates M&M's",
    price: 28000,
    icon: "🍿🥤🍫",
    tag: "MÁS POPULAR"
  },
  {
    id: "snk-popcorn-butter",
    name: "Crispetas Clásicas Mantequilla (Grande)",
    category: "Crispetas",
    description: "Palomitas crujientes con doble baño de mantequilla artesanal CinemaStellar.",
    price: 12000,
    icon: "🍿",
    tag: "FAVORITO"
  },
  {
    id: "snk-popcorn-caramel",
    name: "Crispetas Caramelo & Sal Marina",
    category: "Crispetas",
    description: "Receta especial horneada con caramelo toffee y destellos de sal marina.",
    price: 14000,
    icon: "🍿✨",
    tag: "GOURMET"
  },
  {
    id: "snk-nachos-supreme",
    name: "Nachos Mega Queso & Jalapeños",
    category: "Snacks",
    description: "Totopos crujientes con doble porción de salsa caliente de queso cheddar.",
    price: 16000,
    icon: "🧀",
    tag: "PICANTE"
  },
  {
    id: "snk-hotdog",
    name: "Hot Dog Especial Cinema",
    category: "Snacks",
    description: "Salchicha americana premium, tocineta ahumada, queso fundido y papas ripio.",
    price: 15000,
    icon: "🌭",
    tag: "RECOMENDADO"
  },
  {
    id: "snk-soda-large",
    name: "Gaseosa Grande 32oz Fría",
    category: "Bebidas",
    description: "Coca-Cola Zero, Original, Sprite o Manzana bien helada con hielo estelar.",
    price: 7000,
    icon: "🥤",
    tag: "BEBIDAS"
  },
  {
    id: "snk-mms",
    name: "M&M's Cacahuate 120g",
    category: "Dulces",
    description: "Chocolates rellenos con maní crujiente cubiertos de capa dulce colorida.",
    price: 8000,
    icon: "🍬",
    tag: "DULCES"
  }
];

// Asignación global para uso directo en cliente SPA sin módulos pesados
if (typeof window !== 'undefined') {
  window.CINEMA_MOVIES = CINEMA_MOVIES;
  window.CINEMA_SNACKS = CINEMA_SNACKS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CINEMA_MOVIES, CINEMA_SNACKS };
}
